### ISSUE TITLE
Enhanced Celestials mod conflict with A&D companion mod

### ISSUE THREAD

**Issue by CorgiTaco** [someaddons/AdventuresAndDungeons#15]
You're targeting a now outdated class path in my mod that tbh isn't necessary anymore assuming you did this for some sort of compatibility sake in regards to cancelling sleeping with my mod's blood moon. 

All logs can be found here: https://github.com/CorgiTaco/Enhanced-Celestials/issues/63

**Comment by CorgiTaco** [comment]
Also please rename your class path & jar from `adventuremod` to the actual name of the curse page, it was a nightmare finding the suspect bc `adventuremod` is such a vague name.

**Comment by someaddons** [comment]
Yes I've added a cancel to forges sleeping event a while back because comforts could bypass sleeping on that version. The companion mod is compiled with that version and thus will ofc not work with the newer version. When I update the celestials mod I'll update the companion aswell, till then the pack will work with the version its shipped with.
